### ISSUE TITLE
There is a error in this example

### ISSUE THREAD

**Issue by shinebar** [hadikachmar3/grocery_app_course#2]
<img width="726" alt="image" src="https://github.com/hadikachmar3/grocery_app_course/assets/6315649/55d680b4-6f0e-4167-9db1-5f3517502f5d">

How can I solve this question? thanks.

**Comment by hadikachmar3** [comment]
Hello, I added a detailed lecture on Udemy regarding this, make sure to check it. 
Now Flutter has a built-in widget called badge, which you can use. However, if you want to use the package you can import it as "Your alias". Please take a look at the detailed lectures for details.
BTW you can find this code updated to 3.7 here: https://github.com/hadikachmar3/grocery_app_course/tree/flutter_code_v3.7
You can star the repo so as not to miss any updates.
